name: Close Issues on Merge into Dev Branch

on:
  pull_request:
    types: [closed]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'dev'
    runs-on: ubuntu-latest
    steps:
      - name: Close linked issues
        uses: peter-evans/close-issue@v2
        with:
          issue-number: ${{ github.event.pull_request.body }}
          comment: "This issue has been closed due to a merge into the dev branch."
