name: Close Issues on PR merges that reference the issue number in the PR body
              
            
on:
  pull_request:
    branches: [ master, main, staging, dev ]
    types: [closed]

jobs:
  close-issues:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Close Issue
        uses: peter-evans/close-issue@v3.0.1
        with:
          issue-number: ${{ github.event.pull_request.body }}
          comment: "This issue has been closed due to the merging of PR #${{ github.event.pull_request.number }}."
